javascript_compressor: closure
template_function: _.template
embed_assets: datauri

javascripts:
  core:
    - public/javascripts/application.js
    - public/javascripts/vendor/underscore-*.js
    - public/javascripts/vendor/jquery-*.js
    - public/javascripts/vendor/jquery.ui.core.js
    - public/javascripts/vendor/jquery.ui.widget.js
    - public/javascripts/vendor/jquery.ui.position.js
    - public/javascripts/vendor/jquery.ui.mouse.js
    - public/javascripts/vendor/jquery.ui.sortable.js
    - public/javascripts/vendor/jquery.ui.autocomplete.js
    - public/javascripts/vendor/*.js
    - public/javascripts/lib/*.js
    - public/javascripts/model/*.js
    - public/javascripts/ui/common/*.js
    - public/javascripts/ui/**/*.js
    - public/javascripts/app/**/*.js
    - app/views/jst/workspace/**/*.jst
  editor:
    - public/javascripts/editor/editor_toolbar.js
    - public/javascripts/editor/*.js
    - app/views/jst/editor/*.jst
  search_embed:
    - app/views/jst/embed/search_*.jst
  note_embed:
    - app/views/jst/embed/note_*.jst
  admin:
    - public/javascripts/admin/*.js
    - app/views/admin/*.jst
  ie_only:
    - public/javascripts/ie/*.js
  home:
    - public/javascripts/home/*.js

stylesheets:
  ui:
    - public/stylesheets/common/reset.css
    - public/stylesheets/ui/ui.css
    - public/stylesheets/ui/*.css
  workspace:
    - public/stylesheets/pages/workspace.css
  empty:
    - public/stylesheets/pages/empty.css
  admin:
    - public/stylesheets/pages/admin.css
  home:
    - public/stylesheets/pages/home.css

  viewer_editing:
    - public/stylesheets/pages/viewer_editing.css
  ie_only:
    - public/stylesheets/common/ie.css
