javascript_compressor: closure
template_function: _.template
embed_assets: on

javascripts:
  core:
    - public/javascripts/application.js
    - public/javascripts/vendor/jquery-1.3.2.js
    - public/javascripts/vendor/*.js
    - public/javascripts/lib/bindable.js
    - public/javascripts/lib/set.js
    - public/javascripts/lib/*.js
    - public/javascripts/model/*.js
    - public/javascripts/ui/common/*.js
    - public/javascripts/ui/**/*.js
    - public/javascripts/app/**/*.js
    - app/views/jst/**/*.jst
  admin:
    - public/javascripts/admin/*.js
    - app/views/admin/*.jst
  ie_only:
    - public/javascripts/ie/*.js

stylesheets:
  ui:
    - public/stylesheets/common/reset.css
    - public/stylesheets/ui/*.css
  workspace:
    - public/stylesheets/pages/workspace.css
  empty:
    - public/stylesheets/pages/empty.css
  admin:
    - public/stylesheets/pages/admin.css
  static:
    - public/stylesheets/common/reset.css
    - public/stylesheets/pages/static.css
    - public/stylesheets/ui/icons.css
    - public/stylesheets/ui/help.css
  viewer_editing:
    - public/stylesheets/ui/ui.css
    - public/stylesheets/ui/icons.css
    - public/stylesheets/pages/viewer_editing.css
  ie_only:
    - public/stylesheets/common/ie.css
