javascript_compressor: closure
template_function: _.template
embed_assets: datauri

javascripts:
  core:
    - public/javascripts/application.js
    - public/javascripts/vendor/underscore-*.js
    - public/javascripts/vendor/jquery-*.js
    - public/javascripts/vendor/jquery.ui.core.js
    - public/javascripts/vendor/jquery.ui.widget.js
    - public/javascripts/vendor/jquery.ui.position.js
    - public/javascripts/vendor/jquery.ui.mouse.js
    - public/javascripts/vendor/jquery.ui.sortable.js
    - public/javascripts/vendor/jquery.ui.autocomplete.js
    - public/javascripts/vendor/*.js
    - public/javascripts/lib/*.js
    - public/javascripts/translations/eng.js
    - public/javascripts/translations/spa.js
    - public/javascripts/model/*.js
    - public/javascripts/ui/common/*.js
    - public/javascripts/ui/**/*.js
    - public/javascripts/app/**/*.js
    - app/views/jst/workspace/**/*.jst
    - public/javascripts/viewer
  editor:
    - public/javascripts/editor/editor_toolbar.js
    - public/javascripts/editor/*.js
    - app/views/jst/editor/*.jst
  search_embed:
    - app/views/jst/embed/search_*.jst
  note_embed:
    - app/views/jst/embed/note_*.jst
  admin:
    - public/javascripts/admin/*.js
    - app/views/admin/*.jst
  ie_only:
    - public/javascripts/ie/*.js
  dev_only:
    - public/javascripts/dev/*.js
  home:
    - public/javascripts/home/*.js
  embedded_login:
    - public/javascripts/vendor/json2.js
    - public/javascripts/vendor/jquery-*.js
    - public/javascripts/embed/easy_xdm.js
    - public/javascripts/embed/embedded_login.js

stylesheets:
  ui:
    - public/stylesheets/common/reset.css
    - public/stylesheets/ui/ui.css
    - public/stylesheets/ui/*.css
    - public/stylesheets/vendor/*.css
  authentication:
    - public/stylesheets/pages/workspace.css
  workspace:
    - public/stylesheets/pages/workspace.css
  empty:
    - public/stylesheets/pages/empty.css
  admin:
    - public/stylesheets/pages/admin.css
    - public/stylesheets/pages/admin_featured_reports.css
  home:
    - public/stylesheets/pages/home.css
  embedded_login:
    - public/stylesheets/pages/embedded_login.css
  viewer_editing:
    - public/stylesheets/pages/viewer_editing.css
  ie_only:
    - public/stylesheets/common/ie.css
