defaults: &defaults
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  pool: 5
  username: <%= DC::SECRETS['username'] %>
  password: <%= DC::SECRETS['db_password'] %>
  allow_concurrency: true

development:
  <<: *defaults
  database: dcloud_analytics_development

staging:
  <<: *defaults
  host: staging.documentcloud.org
  database: dcloud_analytics_staging

production:
  <<: *defaults
  host: <%= DC::SECRETS['db_host'] %>
  database: dcloud_analytics_production

test:
  <<: *defaults
  database: dcloud_analytics_test

elastic:
  <<: *defaults
  host: <%= DC::SECRETS['db_host'] %>
  database: dcloud_analytics_production
