<% secrets = YAML.load_file('./secrets/secrets.yml')[ENV['RAILS_ENV'] || "development"] %>
defaults: &defaults
  cloud_crowd_server:   http://dev.dcloud.org:8080
  server_root:          dev.dcloud.org
  aws_zone:             us-east-1c
  preconfigured_ami_id: ami-e39ef78a

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: ec2-50-16-197-147.compute-1.amazonaws.com:8080
  server_root:        staging.documentcloud.org
  asset_root:         "//s3.amazonaws.com/dcloud_staging"

production:
  <<: *defaults
  cloud_crowd_server: <%= secrets['db_host'] %>:8080
  server_root:        www.documentcloud.org
  asset_root:         "//s3.amazonaws.com/s3.documentcloud.org"
  db_volume_id:       vol-d4c305bd

test:
  <<: *defaults