production:
  solr:
    hostname: ec2-184-73-200-49.compute-1.amazonaws.com
    port: 7377
    path: /solr/collection1
    read_timeout: 2
    open_timeout: 1.5
    log_level: INFO
    min_memory: 20M
    max_memory: 500M
    pid_dir: tmp/pids

development:
  solr:
    hostname: localhost
    port: 7377
    log_level: ALL
    path: /solr/collection1
    pid_dir: tmp/pids

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/collection1
    pid_dir: tmp/pids

staging:
  solr:
    hostname: ec2-50-16-197-147.compute-1.amazonaws.com
    port: 7377
    log_level: WARNING
    pid_dir: tmp/pids
    path: /solr/collection1
